-- MySQL Script generated by MySQL Workbench
-- Sun Oct 22 17:30:01 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema cakephp_test
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema cakephp_test
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `cakephp_test` DEFAULT CHARACTER SET utf8 ;
USE `cakephp_test` ;

-- -----------------------------------------------------
-- Table `cakephp_test`.`images`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cakephp_test`.`images` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `filename` VARCHAR(255) NOT NULL,
  `dir` VARCHAR(255) NULL,
  `imgw` INT NULL,
  `imgh` INT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
